[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MohamedAfifii/Route-AI-for-Self-Driving-Cars-Course-Material/blob/main/Week-1/numpy_task.ipynb)

# Notes
- Erase every `None` in the code cells below, and put in your own line of code.
- Do **NOT** use any loops
- Do **NOT** write manual loops. For example do not do something like

```py
a = np.ones(3)
b = np.ones(3)
c = np.zeros(3)

c[0] = a[0] + b[0]
c[1] = a[1] + b[1]
c[2] = a[2] + b[2]
```

# Basics

In [ ]:
import numpy as np

In [ ]:
#Replace 'None' with the appropriate expression

a = None #Array of shape (4,) full of zeros
b = None #Array of shape (3,4) full of ones
c = None #Array of shape (5,) holding the values from 0 to 4

print(a)
print()
print(b)
print()
print(c)

# Expected output:
# [0. 0. 0. 0.]

# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

# [0 1 2 3 4]

In [ ]:
a = np.arange(10)
b = np.arange(10)

c = None #Dot product between a and b. Use np.dot
print(c)

#Expected output: 285

In [ ]:
a = np.arange(10)
b = np.arange(10)

c = None #Dot product between a and b. Do NOT use np.dot. Hint: Use element-wise multiplication
print(c)

#Expected output: 285

# Axis

In [ ]:
a = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

b = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

c = None  #c[i] = dotProduct(i'th column in a, i'th column in b)
print(c)

#Expected output:
#[ 66  93 126]

In [ ]:
a = np.array([[4, 6, 1],
              [1, 3, 9],
              [5, -1, -7]])

b = None  # b[i]: The index (column number) of the largest element in the row a[i]
print(b)

# Expected output:
# [1 2 0]

# Explanation: For the 0'th row of the array a, the largest element is 6 which is at position 1. So b[0] = 1

# Indexing

In [ ]:
#              0  1  2  3  4  5   6  7
a = np.array([-5, 1, 4, 6, 9, 2, -4, 7])
n = len(a)  # 8

# In one line, put zeros at even indices in the array. 
# Hint: use np.arange with step = 2
raise NotImplementedError # Remove this line and put your code here

print(a)
# Expected output:
# [0 1 0 6 0 2 0 7]

In [ ]:
a = np.array([-5, 1, 4, 6, 9, 2, -4, 7])

# Replace all negative numbers in the array with zeros.
# Hint: The < operator returns a binary mask
raise NotImplementedError # Remove this line and put your code here

print(a)
# Expected output:
# [0 1 4 6 9 2 0 7]

# Broadcasting

In [ ]:
a = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

b = np.array([10,100,1000])

c = None  #c[i][j] = a[i][j] + b[j]
print(c)

#Expected output:
# [[  11  102 1003]
#  [  14  105 1006]
#  [  17  108 1009]]

In [ ]:
a = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

b = np.array([10,100,1000])

c = None  #c[i][j] = a[i][j] + b[i]
print(c)

#Expected output:
# [[  11   12   13]
#  [ 104  105  106]
#  [1007 1008 1009]]

In [ ]:
a = np.array([[3, 4],
              [1, 9],
              [7, 5]])

b = np.array([5, 6])

c = None  #c[i] = distance(a[i], b). Note: distance = sqrt(delta_x^2 + delta_y^2)
print(c)

# Expected output:
[2.82842712 5.         2.23606798]

In [ ]:
a = np.arange(5)
b = np.arange(3)

#c[i][j] = a[i]*b[j]
#This may take more than one line of code. Hint: Reshape the vectors to use broadcasting
c = None
print(c)

#Expected output:
# [[0 0 0]
#  [0 1 2]
#  [0 2 4]
#  [0 3 6]
#  [0 4 8]]